/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CreateUser
 * @category generated
 */
export const createUserStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'CreateUserInstructionArgs'
)
/**
 * Accounts required by the _createUser_ instruction
 *
 * @property [_writable_] poolInfo
 * @property [_writable_, **signer**] userWallet
 * @property [_writable_] userStakingsInfo
 * @category Instructions
 * @category CreateUser
 * @category generated
 */
export type CreateUserInstructionAccounts = {
  poolInfo: web3.PublicKey
  userWallet: web3.PublicKey
  userStakingsInfo: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createUserInstructionDiscriminator = [
  108, 227, 130, 130, 252, 109, 75, 218,
]

/**
 * Creates a _CreateUser_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category CreateUser
 * @category generated
 */
export function createCreateUserInstruction(
  accounts: CreateUserInstructionAccounts,
  programId = new web3.PublicKey('Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS')
) {
  const [data] = createUserStruct.serialize({
    instructionDiscriminator: createUserInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.poolInfo,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userWallet,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.userStakingsInfo,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
