env:
  browser: true
  es2021: true
  node: true
extends:
  - prettier
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - prettier
  - react
  - '@typescript-eslint'
rules:
  prettier/prettier:
    - error
  arrow-spacing:
    - warn
    - before: true
      after: true
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  comma-spacing: error
  comma-style: error
  curly:
    - error
    - multi-line
    - consistent
  dot-location:
    - error
    - property
  handle-callback-err: 'off'
  keyword-spacing: error
  max-nested-callbacks:
    - error
    - max: 4
  max-statements-per-line:
    - error
    - max: 2
  no-console: error
  no-empty-function: error
  no-floating-decimal: error
  no-inline-comments: error
  no-lonely-if: error
  no-multi-spaces: error
  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 1
      maxBOF: 0
  no-shadow:
    - error
    - allow:
      - err
      - resolve
      - reject
  no-trailing-spaces:
    - error
  no-var: error
  prefer-const: error
  space-before-blocks: error
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  yoda: error
globals:
  document: readonly
  window: readonly
