/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ClaimRewards
 * @category generated
 */
export const claimRewardsStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'ClaimRewardsInstructionArgs'
)
/**
 * Accounts required by the _claimRewards_ instruction
 *
 * @property [_writable_, **signer**] authority
 * @property [] globalState
 * @property [_writable_] subOffer
 * @property [_writable_] rewardVault
 * @property [] chainlinkProgram
 * @property [] solFeed
 * @property [] usdcFeed
 * @property [_writable_] lenderRewardVault
 * @property [_writable_] borrowerRewardVault
 * @property [] clock
 * @category Instructions
 * @category ClaimRewards
 * @category generated
 */
export type ClaimRewardsInstructionAccounts = {
  authority: web3.PublicKey
  globalState: web3.PublicKey
  subOffer: web3.PublicKey
  rewardVault: web3.PublicKey
  chainlinkProgram: web3.PublicKey
  solFeed: web3.PublicKey
  usdcFeed: web3.PublicKey
  lenderRewardVault: web3.PublicKey
  borrowerRewardVault: web3.PublicKey
  clock: web3.PublicKey
}

export const claimRewardsInstructionDiscriminator = [
  4, 144, 132, 71, 116, 23, 151, 80,
]

/**
 * Creates a _ClaimRewards_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category ClaimRewards
 * @category generated
 */
export function createClaimRewardsInstruction(
  accounts: ClaimRewardsInstructionAccounts
) {
  const {
    authority,
    globalState,
    subOffer,
    rewardVault,
    chainlinkProgram,
    solFeed,
    usdcFeed,
    lenderRewardVault,
    borrowerRewardVault,
    clock,
  } = accounts

  const [data] = claimRewardsStruct.serialize({
    instructionDiscriminator: claimRewardsInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: authority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: globalState,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: subOffer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: rewardVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: chainlinkProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: solFeed,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: usdcFeed,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: lenderRewardVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: borrowerRewardVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: clock,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId: new web3.PublicKey(
      '6oVXrGCdtnTUR6xCvn2Z3f2CYaiboAGar1DKxzeX8QYh'
    ),
    keys,
    data,
  })
  return ix
}
