/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ClaimExpiredCollateral
 * @category generated
 */
export const claimExpiredCollateralStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'ClaimExpiredCollateralInstructionArgs'
)
/**
 * Accounts required by the _claimExpiredCollateral_ instruction
 *
 * @property [_writable_, **signer**] superOwner
 * @property [] globalState
 * @property [_writable_] treasuryWallet
 * @property [_writable_] offer
 * @property [_writable_] subOffer
 * @property [_writable_] userNftVault
 * @property [_writable_] borrowerNftVault
 * @property [] nftMint
 * @property [] edition
 * @property [] metadataProgram
 * @property [] clock
 * @category Instructions
 * @category ClaimExpiredCollateral
 * @category generated
 */
export type ClaimExpiredCollateralInstructionAccounts = {
  superOwner: web3.PublicKey
  globalState: web3.PublicKey
  treasuryWallet: web3.PublicKey
  offer: web3.PublicKey
  subOffer: web3.PublicKey
  userNftVault: web3.PublicKey
  borrowerNftVault: web3.PublicKey
  nftMint: web3.PublicKey
  edition: web3.PublicKey
  metadataProgram: web3.PublicKey
  clock: web3.PublicKey
}

export const claimExpiredCollateralInstructionDiscriminator = [
  43, 176, 249, 0, 163, 168, 177, 195,
]

/**
 * Creates a _ClaimExpiredCollateral_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category ClaimExpiredCollateral
 * @category generated
 */
export function createClaimExpiredCollateralInstruction(
  accounts: ClaimExpiredCollateralInstructionAccounts
) {
  const {
    superOwner,
    globalState,
    treasuryWallet,
    offer,
    subOffer,
    userNftVault,
    borrowerNftVault,
    nftMint,
    edition,
    metadataProgram,
    clock,
  } = accounts

  const [data] = claimExpiredCollateralStruct.serialize({
    instructionDiscriminator: claimExpiredCollateralInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: superOwner,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: globalState,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: treasuryWallet,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: offer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: subOffer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: userNftVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: borrowerNftVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: nftMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: edition,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: metadataProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: clock,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId: new web3.PublicKey(
      '6oVXrGCdtnTUR6xCvn2Z3f2CYaiboAGar1DKxzeX8QYh'
    ),
    keys,
    data,
  })
  return ix
}
