/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import {
  ApprovalForUpdate,
  approvalForUpdateBeet,
} from '../types/ApprovalForUpdate'
import {
  InterestRateFraction,
  interestRateFractionBeet,
} from '../types/InterestRateFraction'
import { ScoreMultiplier, scoreMultiplierBeet } from '../types/ScoreMultiplier'
import {
  FeeReductionLevels,
  feeReductionLevelsBeet,
} from '../types/FeeReductionLevels'

/**
 * Arguments used to create {@link UpdatePoolConfigsInfo}
 * @category Accounts
 * @category generated
 */
export type UpdatePoolConfigsInfoArgs = {
  proposalAuthorityWallet: web3.PublicKey
  poolInfo: web3.PublicKey
  bump: number
  approvalsReceived: number
  approvalsNeededForUpdate: number
  updateApproved: boolean
  updateDone: boolean
  approvals: ApprovalForUpdate[]
  interestRateFraction: InterestRateFraction
  scoreMultiplier: ScoreMultiplier
  profileLevelMultiplier: FeeReductionLevels
  unstakePenalityBasisPoints: beet.bignum
  pausePool: boolean
}

export const updatePoolConfigsInfoDiscriminator = [
  212, 83, 188, 189, 114, 42, 41, 196,
]
/**
 * Holds the data for the {@link UpdatePoolConfigsInfo} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class UpdatePoolConfigsInfo implements UpdatePoolConfigsInfoArgs {
  private constructor(
    readonly proposalAuthorityWallet: web3.PublicKey,
    readonly poolInfo: web3.PublicKey,
    readonly bump: number,
    readonly approvalsReceived: number,
    readonly approvalsNeededForUpdate: number,
    readonly updateApproved: boolean,
    readonly updateDone: boolean,
    readonly approvals: ApprovalForUpdate[],
    readonly interestRateFraction: InterestRateFraction,
    readonly scoreMultiplier: ScoreMultiplier,
    readonly profileLevelMultiplier: FeeReductionLevels,
    readonly unstakePenalityBasisPoints: beet.bignum,
    readonly pausePool: boolean
  ) {}

  /**
   * Creates a {@link UpdatePoolConfigsInfo} instance from the provided args.
   */
  static fromArgs(args: UpdatePoolConfigsInfoArgs) {
    return new UpdatePoolConfigsInfo(
      args.proposalAuthorityWallet,
      args.poolInfo,
      args.bump,
      args.approvalsReceived,
      args.approvalsNeededForUpdate,
      args.updateApproved,
      args.updateDone,
      args.approvals,
      args.interestRateFraction,
      args.scoreMultiplier,
      args.profileLevelMultiplier,
      args.unstakePenalityBasisPoints,
      args.pausePool
    )
  }

  /**
   * Deserializes the {@link UpdatePoolConfigsInfo} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [UpdatePoolConfigsInfo, number] {
    return UpdatePoolConfigsInfo.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link UpdatePoolConfigsInfo} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<UpdatePoolConfigsInfo> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(
        `Unable to find UpdatePoolConfigsInfo account at ${address}`
      )
    }
    return UpdatePoolConfigsInfo.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(
      programId,
      updatePoolConfigsInfoBeet
    )
  }

  /**
   * Deserializes the {@link UpdatePoolConfigsInfo} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [UpdatePoolConfigsInfo, number] {
    return updatePoolConfigsInfoBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link UpdatePoolConfigsInfo} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return updatePoolConfigsInfoBeet.serialize({
      accountDiscriminator: updatePoolConfigsInfoDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link UpdatePoolConfigsInfo} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: UpdatePoolConfigsInfoArgs) {
    const instance = UpdatePoolConfigsInfo.fromArgs(args)
    return updatePoolConfigsInfoBeet.toFixedFromValue({
      accountDiscriminator: updatePoolConfigsInfoDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link UpdatePoolConfigsInfo} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: UpdatePoolConfigsInfoArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      UpdatePoolConfigsInfo.byteSize(args),
      commitment
    )
  }

  /**
   * Returns a readable version of {@link UpdatePoolConfigsInfo} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      proposalAuthorityWallet: this.proposalAuthorityWallet.toBase58(),
      poolInfo: this.poolInfo.toBase58(),
      bump: this.bump,
      approvalsReceived: this.approvalsReceived,
      approvalsNeededForUpdate: this.approvalsNeededForUpdate,
      updateApproved: this.updateApproved,
      updateDone: this.updateDone,
      approvals: this.approvals,
      interestRateFraction: this.interestRateFraction,
      scoreMultiplier: this.scoreMultiplier,
      profileLevelMultiplier: this.profileLevelMultiplier,
      unstakePenalityBasisPoints: (() => {
        const x = <{ toNumber: () => number }>this.unstakePenalityBasisPoints
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      pausePool: this.pausePool,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const updatePoolConfigsInfoBeet = new beet.FixableBeetStruct<
  UpdatePoolConfigsInfo,
  UpdatePoolConfigsInfoArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['proposalAuthorityWallet', beetSolana.publicKey],
    ['poolInfo', beetSolana.publicKey],
    ['bump', beet.u8],
    ['approvalsReceived', beet.u8],
    ['approvalsNeededForUpdate', beet.u8],
    ['updateApproved', beet.bool],
    ['updateDone', beet.bool],
    ['approvals', beet.array(approvalForUpdateBeet)],
    ['interestRateFraction', interestRateFractionBeet],
    ['scoreMultiplier', scoreMultiplierBeet],
    ['profileLevelMultiplier', feeReductionLevelsBeet],
    ['unstakePenalityBasisPoints', beet.u128],
    ['pausePool', beet.bool],
  ],
  UpdatePoolConfigsInfo.fromArgs,
  'UpdatePoolConfigsInfo'
)
