/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'
export type ApprovalForUpdate = {
  authority: web3.PublicKey
  approved: boolean
}

/**
 * @category userTypes
 * @category generated
 */
export const approvalForUpdateBeet = new beet.BeetArgsStruct<ApprovalForUpdate>(
  [
    ['authority', beetSolana.publicKey],
    ['approved', beet.bool],
  ],
  'ApprovalForUpdate'
)
