/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import {
  LockedStakingAccount,
  lockedStakingAccountBeet,
} from './LockedStakingAccount'
export type LockedStakingsData = {
  numActiveLockedStakingAccounts: number
  currentMaxLockedStakingsPossible: number
  lockedStakingsData: LockedStakingAccount[]
}

/**
 * @category userTypes
 * @category generated
 */
export const lockedStakingsDataBeet =
  new beet.FixableBeetArgsStruct<LockedStakingsData>(
    [
      ['numActiveLockedStakingAccounts', beet.u16],
      ['currentMaxLockedStakingsPossible', beet.u16],
      ['lockedStakingsData', beet.array(lockedStakingAccountBeet)],
    ],
    'LockedStakingsData'
  )
