/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type NumDenPair = {
  numerator: beet.bignum
  denominator: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const numDenPairBeet = new beet.BeetArgsStruct<NumDenPair>(
  [
    ['numerator', beet.u128],
    ['denominator', beet.u128],
  ],
  'NumDenPair'
)
