/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type PoolStats = {
  numStakingUsers: beet.bignum
  numLockedStakingUsers: beet.bignum
  numActiveStakingAccounts: beet.bignum
  numUniqueStakersLifetime: beet.bignum
  totalTokensDepositedLifetime: beet.bignum
  totalTokensWithdrawnLifetime: beet.bignum
  totalRewardsWithdrawnLifetime: beet.bignum
  totalRewardsDepositedLifetime: beet.bignum
  totalPenalityTokensLifetime: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const poolStatsBeet = new beet.BeetArgsStruct<PoolStats>(
  [
    ['numStakingUsers', beet.u128],
    ['numLockedStakingUsers', beet.u128],
    ['numActiveStakingAccounts', beet.u128],
    ['numUniqueStakersLifetime', beet.u128],
    ['totalTokensDepositedLifetime', beet.u128],
    ['totalTokensWithdrawnLifetime', beet.u128],
    ['totalRewardsWithdrawnLifetime', beet.u128],
    ['totalRewardsDepositedLifetime', beet.u128],
    ['totalPenalityTokensLifetime', beet.u128],
  ],
  'PoolStats'
)
