/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type ProfileLevelMultiplier = {
  minUnlocScore: beet.bignum
  feeReductionBasisPoints: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const profileLevelMultiplierBeet =
  new beet.BeetArgsStruct<ProfileLevelMultiplier>(
    [
      ['minUnlocScore', beet.u128],
      ['feeReductionBasisPoints', beet.u128],
    ],
    'ProfileLevelMultiplier'
  )
