/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import {
  FlexiStakingAccount,
  flexiStakingAccountBeet,
} from './FlexiStakingAccount'
import {
  LiqMinRwdsStakingAccount,
  liqMinRwdsStakingAccountBeet,
} from './LiqMinRwdsStakingAccount'
import {
  LockedStakingsData,
  lockedStakingsDataBeet,
} from './LockedStakingsData'
export type StakingAccounts = {
  flexi: FlexiStakingAccount
  liqMinRwds: LiqMinRwdsStakingAccount
  locked: LockedStakingsData
}

/**
 * @category userTypes
 * @category generated
 */
export const stakingAccountsBeet =
  new beet.FixableBeetArgsStruct<StakingAccounts>(
    [
      ['flexi', flexiStakingAccountBeet],
      ['liqMinRwds', liqMinRwdsStakingAccountBeet],
      ['locked', lockedStakingsDataBeet],
    ],
    'StakingAccounts'
  )
