/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import {
  AllowedStakingDurationMonths,
  allowedStakingDurationMonthsBeet,
} from './AllowedStakingDurationMonths'
export type StakingData = {
  initialTokensStaked: beet.bignum
  accountLastUpdatedAt: beet.bignum
  lockDuration: AllowedStakingDurationMonths
}

/**
 * @category userTypes
 * @category generated
 */
export const stakingDataBeet = new beet.BeetArgsStruct<StakingData>(
  [
    ['initialTokensStaked', beet.u64],
    ['accountLastUpdatedAt', beet.u64],
    ['lockDuration', allowedStakingDurationMonthsBeet],
  ],
  'StakingData'
)
