/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type UnlocScoreData = {
  userScore: beet.bignum
  lastUpdatedAt: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const unlocScoreDataBeet = new beet.BeetArgsStruct<UnlocScoreData>(
  [
    ['userScore', beet.u128],
    ['lastUpdatedAt', beet.u64],
  ],
  'UnlocScoreData'
)
