/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import {
  InterestRateFraction,
  interestRateFractionBeet,
} from './InterestRateFraction'
import { ScoreMultiplier, scoreMultiplierBeet } from './ScoreMultiplier'
import {
  FeeReductionLevels,
  feeReductionLevelsBeet,
} from './FeeReductionLevels'
export type UpdatePoolArgs = {
  interestRateFraction: InterestRateFraction
  scoreMultiplier: ScoreMultiplier
  profileLevelMultiplier: FeeReductionLevels
  unstakePenalityBasisPoints: beet.bignum
  pausePool: boolean
}

/**
 * @category userTypes
 * @category generated
 */
export const updatePoolArgsBeet = new beet.BeetArgsStruct<UpdatePoolArgs>(
  [
    ['interestRateFraction', interestRateFractionBeet],
    ['scoreMultiplier', scoreMultiplierBeet],
    ['profileLevelMultiplier', feeReductionLevelsBeet],
    ['unstakePenalityBasisPoints', beet.u128],
    ['pausePool', beet.bool],
  ],
  'UpdatePoolArgs'
)
